# Generated by Django 5.0.1 on 2024-01-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
