# Generated by Django 5.0.1 on 2024-01-25 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_time',
            new_name='deadline',
        ),
    ]
